#!/usr/bin/env bash
#installing nginx and performing a 301 redirection

sudo apt-get update
sudo apt-get -y install nginx

echo "Hello world!" | sudo tee /var/www/html/index.html

string_for_replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/TimmyAkinyemi123?tab=repositories permanent;"
sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default
sudo service nginx restart
