#!/usr/bin/env bash
# Configuring web-01 and web-02 to have an HTTP response header

# updating packages
sudo apt-get update
sudo apt-get install -y nginx

# creating an index.html page
echo "Hello world!" | sudo tee /var/www/html/index.html

#performing redirections
string_for_replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/TimmyAkinyemi123?tab=repositories permanent;"
sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

#creating a 404 page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
string_for_replacement="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\troot \/var\/www\/html;n\t\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$string_for_replacement/" /etc/nginx/sites-enabled/default

# Creating a custom HTTP response header
sudo sed -i "/server_name _/a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-enabled/default

#testing for syntax errors
sudo nginx -t

#restarting engine after modification
sudo service nginx restart
