#!/usr/bin/env bash

# Install HAProxy
sudo apt update
sudo apt install -y haproxy

# Configure HAProxy
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.backup
sudo cat <<EOF | sudo tee /etc/haproxy/haproxy.cfg
global
    log /dev/log local0
    log /dev/log local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log global
    mode http
    option httplog
    option dontlognull
    timeout connect 5000
    timeout client 50000
    timeout server 50000

frontend http_front
    bind *:80
    stats uri /haproxy?stats
    default_backend http_back

backend http_back
    balance roundrobin
    server web-01 281767-web-01:80 check
    server web-02 281767-web-02:80 check
EOF

# Verify and reload HAProxy
sudo haproxy -c -f /etc/haproxy/haproxy.cfg
sudo systemctl restart haproxy

# Ensure HAProxy init script management
sudo systemctl enable haproxy

# Ensure hostnames are properly configured
sudo hostnamectl set-hostname 281767-lb-01
echo "281767-lb-01" | sudo tee /etc/hostname
sudo sed -i '/127.0.0.1/c\127.0.0.1 localhost 281767-lb-01' /etc/hosts

# Restart to apply hostname changes
sudo systemctl restart systemd-hostnamed
